README.md
library/src/main/java/com/kizitonwose/calendarview/CalendarView.kt
library/src/main/java/com/kizitonwose/calendarview/ui/CalendarAdapter.kt
sample/src/androidTest/java/com/kizitonwose/calenderviewsample/CalenderViewTests.kt
sample/src/main/java/com/kizitonwose/calendarviewsample/Example5Fragment.kt

[Release notes](https://github.com/kizitonwose/CalendarView/releases/tag/0.1.1)

Release 0.1.1

---

library/src/main/java/com/kizitonwose/calendarview/CalendarView.kt
library/src/main/java/com/kizitonwose/calendarview/ui/CalendarAdapter.kt
library/src/main/java/com/kizitonwose/calendarview/ui/WeekHolder.kt

[Release notes](https://github.com/kizitonwose/CalendarView/releases/tag/0.1.2)

Release 0.1.2

---

library/src/main/java/com/kizitonwose/calendarview/ui/CalendarAdapter.kt

[Release notes](https://github.com/kizitonwose/CalendarView/releases/tag/0.2.1) 
Closes #21

Release 0.2.1

---

library/src/test/java/com/kizitonwose/calenderview/CalenderViewTests.kt
sample/src/androidTest/java/com/kizitonwose/calenderviewsample/CalenderViewTests.kt

- Add tests for `maxRowCount` and `hasBoundaries` properties. 
- Add tests for finding first/last visible day/month.

Add more tests.

---

library/src/main/java/com/kizitonwose/calendarview/CalendarView.kt

[Release notes](https://github.com/kizitonwose/CalendarView/releases/tag/0.2.2)
Closes #26

Release 0.2.2

---

README.md
build.gradle
library/build.gradle
library/src/main/java/com/kizitonwose/calendarview/CalendarView.kt

[Release notes](https://github.com/kizitonwose/CalendarView/releases/tag/0.2.3)

Release 0.2.3

---

library/src/main/java/com/kizitonwose/calendarview/ui/CalendarLayoutManager.kt

[Release notes](https://github.com/kizitonwose/CalendarView/releases/tag/0.2.4)
Closes #29

Release 0.2.4

---

.travis.yml
library/src/main/java/com/kizitonwose/calendarview/ui/CalendarAdapter.kt

[Release notes](https://github.com/kizitonwose/CalendarView/releases/tag/0.2.5)
Closes #37

Release 0.2.5

---

library/src/main/java/com/kizitonwose/calendarview/CalendarView.kt
library/src/main/java/com/kizitonwose/calendarview/ui/CalendarLayoutManager.kt

[Release notes](https://github.com/kizitonwose/CalendarView/releases/tag/0.2.6)
Closes #35

Release 0.2.6

---

library/src/main/java/com/kizitonwose/calendarview/CalendarView.kt
sample/src/androidTest/java/com/kizitonwose/calenderviewsample/CalenderViewTests.kt

[Release notes](https://github.com/kizitonwose/CalendarView/releases/tag/0.2.7)
Closes #44

Release 0.2.7

---

library/src/main/java/com/kizitonwose/calendarview/CalendarView.kt

The method changes startMonth and/or endMonth with minimal updates
to the underlying RecyclerView.
This fixes #67.

Add an updateRange method.

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
library/build.gradle
library/src/main/java/com/kizitonwose/calendarview/CalendarView.kt
library/src/main/java/com/kizitonwose/calendarview/model/MonthConfig.kt
sample/build.gradle
sample/src/main/java/com/kizitonwose/calendarviewsample/Example1Fragment.kt
sample/src/main/java/com/kizitonwose/calendarviewsample/Example4Fragment.kt
sample/src/main/java/com/kizitonwose/calendarviewsample/Example5Fragment.kt

[Release notes](https://github.com/kizitonwose/CalendarView/releases/tag/0.2.9)
Closes #67

Release 0.2.9

---

build.gradle
library/src/main/java/com/kizitonwose/calendarview/model/MonthConfig.kt
library/src/test/java/com/kizitonwose/calenderview/CalenderViewTests.kt

[Release notes](https://github.com/kizitonwose/CalendarView/releases/tag/0.3.1)
Closes #83

Release 0.3.1

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
library/build.gradle
library/src/main/java/com/kizitonwose/calendarview/CalendarView.kt
library/src/main/java/com/kizitonwose/calendarview/ui/CalendarAdapter.kt
library/src/main/java/com/kizitonwose/calendarview/ui/WeekHolder.kt
sample/src/main/java/com/kizitonwose/calendarviewsample/Example1Fragment.kt
sample/src/main/java/com/kizitonwose/calendarviewsample/HomeActivity.kt
sample/src/main/java/com/kizitonwose/calendarviewsample/HomeOptionsAdapter.kt
sample/src/main/res/layout/example_1_fragment.xml

[Release notes.](https://github.com/kizitonwose/CalendarView/releases/tag/0.3.3)

Release 0.3.3

---

library/build.gradle
library/src/main/java/com/kizitonwose/calendarview/CalendarView.kt
library/src/main/java/com/kizitonwose/calendarview/ui/CalendarAdapter.kt
library/src/main/java/com/kizitonwose/calendarview/ui/CalenderPageSnapHelper.kt
library/src/main/res/values/attrs.xml

[Release notes](https://github.com/kizitonwose/CalendarView/releases/tag/0.3.4)

Release 0.3.4

---

library/src/main/java/com/kizitonwose/calendarview/CalendarView.kt
library/src/main/java/com/kizitonwose/calendarview/ui/DayHolder.kt
library/src/main/java/com/kizitonwose/calendarview/ui/WeekHolder.kt

[Release notes](https://github.com/kizitonwose/CalendarView/releases/tag/0.3.5)

Release 0.3.5

---

library/src/main/java/com/kizitonwose/calendarview/ui/CalendarAdapter.kt
library/src/main/java/com/kizitonwose/calendarview/ui/CalendarLayoutManager.kt
library/src/main/java/com/kizitonwose/calendarview/ui/DayHolder.kt
library/src/main/java/com/kizitonwose/calendarview/ui/MonthViewHolder.kt
library/src/main/java/com/kizitonwose/calendarview/ui/WeekHolder.kt
sample/src/androidTest/java/com/kizitonwose/calenderviewsample/CalenderViewTests.kt

Eliminate redundant FrameLayout

---

README.md
dependencies.gradle
library/build.gradle
library/src/main/java/com/kizitonwose/calendarview/CalendarView.kt
library/src/main/java/com/kizitonwose/calendarview/model/MonthConfig.kt
library/src/main/java/com/kizitonwose/calendarview/ui/CalendarAdapter.kt
library/src/main/java/com/kizitonwose/calendarview/ui/CalendarLayoutManager.kt
library/src/main/java/com/kizitonwose/calendarview/ui/DayHolder.kt
library/src/main/java/com/kizitonwose/calendarview/ui/MonthViewHolder.kt
library/src/main/java/com/kizitonwose/calendarview/ui/WeekHolder.kt
library/src/main/java/com/kizitonwose/calendarview/utils/Extensions.kt
library/src/main/java/com/kizitonwose/calendarview/utils/Size.kt
sample/build.gradle
sample/src/androidTest/java/com/kizitonwose/calenderviewsample/CalenderViewTests.kt
sample/src/main/java/com/kizitonwose/calendarviewsample/Example1Fragment.kt
sample/src/main/java/com/kizitonwose/calendarviewsample/Example6Fragment.kt
sample/src/main/java/com/kizitonwose/calendarviewsample/Example7Fragment.kt

[Release notes](https://github.com/kizitonwose/CalendarView/releases/tag/0.4.1)
closes #181, closes #184 and closes #187

Release 0.4.1

---

library/src/main/java/com/kizitonwose/calendarview/CalendarView.kt
sample/src/androidTest/java/com/kizitonwose/calenderviewsample/CalenderViewTests.kt

[Release notes](https://github.com/kizitonwose/CalendarView/releases/tag/0.4.2)

Release 0.4.2

---

dependencies.gradle
library/src/main/java/com/kizitonwose/calendarview/CalendarView.kt
sample/src/main/java/com/kizitonwose/calendarviewsample/Example3Fragment.kt
sample/src/main/java/com/kizitonwose/calendarviewsample/HomeOptionsAdapter.kt

[Release notes](https://github.com/kizitonwose/CalendarView/releases/tag/0.4.4)

Release 0.4.4

---

library/src/main/java/com/kizitonwose/calendarview/model/Enums.kt

Fix reffered name of PREVIOUS_MONTH to inDates

---

dependencies.gradle
library/src/main/java/com/kizitonwose/calendarview/CalendarView.kt

[Release notes](https://github.com/kizitonwose/CalendarView/releases/tag/0.4.5)
Closes #224 
Closes #218

Release 0.4.5

---

README.md
library/src/main/java/com/kizitonwose/calendarview/CalendarView.kt
library/src/main/java/com/kizitonwose/calendarview/ui/CalendarAdapter.kt
sample/src/androidTest/java/com/kizitonwose/calenderviewsample/CalenderViewTests.kt

[Release notes](https://github.com/kizitonwose/CalendarView/releases/tag/1.0.0)

Release 1.0.0

---

.gitignore
.idea/codeStyles/Project.xml
.idea/codeStyles/codeStyleConfig.xml
.idea/compiler.xml
.idea/dictionaries/kizito_nwose.xml
.idea/gradle.xml
.idea/jarRepositories.xml
.idea/misc.xml
.idea/runConfigurations.xml
.idea/vcs.xml
library/src/main/java/com/kizitonwose/calendarview/CalendarView.kt
library/src/main/java/com/kizitonwose/calendarview/ui/CalendarAdapter.kt
sample/src/main/java/com/kizitonwose/calendarviewsample/Example4Fragment.kt

[Release notes](https://github.com/kizitonwose/CalendarView/releases/tag/1.0.1)

Release 1.0.1

---

library/src/main/java/com/kizitonwose/calendarview/ui/CalendarAdapter.kt
library/src/main/java/com/kizitonwose/calendarview/utils/Extensions.kt

[Release notes](https://github.com/kizitonwose/CalendarView/releases/tag/1.0.2)

Release 1.0.2

---

.idea/codeStyles/Project.xml
library/src/main/java/com/kizitonwose/calendarview/ui/CalendarAdapter.kt
sample/src/main/java/com/kizitonwose/calendarviewsample/Example4Fragment.kt

[Release notes](https://github.com/kizitonwose/CalendarView/releases/tag/1.0.3)

Release 1.0.3

---

.idea/compiler.xml
.idea/jarRepositories.xml
.idea/misc.xml
.idea/runConfigurations.xml
build.gradle
dependencies.gradle
gradle/wrapper/gradle-wrapper.properties
library/src/main/java/com/kizitonwose/calendarview/ui/CalendarAdapter.kt
sample/src/main/res/layout/example_4_fragment.xml

[Release notes](https://github.com/kizitonwose/CalendarView/releases/tag/1.0.4)

Release 1.0.4

---

docs/View.md

Change the code block's syntax highlighting from `kotlin` to `xml`.

docs: Update View.md 

---

README.md

Easier to view versions and apply them here.
https://central.sonatype.com/search?q=g:com.kizitonwose.calendar

Update MavenCentral links

---

build.gradle.kts
buildSrc/src/main/java/com/kizitonwose/calendar/buildsrc/Build.kt
compose-multiplatform/library/build.gradle.kts
compose/build.gradle.kts
core/build.gradle.kts
data/build.gradle.kts
sample/src/androidTest/java/com/kizitonwose/calendar/sample/CalendarViewTests.kt
view/build.gradle.kts

This allows publishing either the android or multiplatform library independently.

Disable publication if needed
